import os


ADDON_DIRECTORY = os.path.dirname(os.path.realpath(__file__))

FBX_HEAD_COLLECTION = 'MRFL_FBX_HEAD'
FBX_BODY_COLLECTION = 'MRFL_FBX_BODY'
TEMPLATE_MESHES_COLLECTION = 'MRFL_TEMPLATE_MESHES'
MRFL_EDIT_MESHES_COLLECTION = 'MRFL_EDIT_MESHES'

# FBX_CLOTH_COLLECTION = "FBX_CLOTH"
# INITIAL_SHAPE_COLLECTION = "INIT_SHAPE"
# FINAL_SHAPE_COLLECTION = "FINAL_SHAPE"
# SYSTEM_COLLECTION = "MRF_SYSTEM_OBJECTS"
# CUSTOM_SHAPES_COLLECTION = "MRF_CUSTOM_SHAPES"
# DEFAULT_EDIT_ID = "skin"

